In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

# 1.1 Из словаря списков (первые 5 сотрудников из Таблицы 1)
data_dict = {
    "ID": [1, 2, 3, 4, 5],
    "Имя": ["Иван", "Ольга", "Алексей", "Мария", "Сергей"],
    "Возраст": [25, 30, 40, 35, 28],
    "Должность": ["Инженер", "Аналитик", "Менеджер", "Программист", "Специалист"],
    "Отдел": ["IT", "Маркетинг", "Продажи", "IT", "HR"],
    "Зарплата": [60000, 75000, 90000, 80000, 50000],
    "Стаж работы": [2, 5, 15, 7, 3]
}
df_dict = pd.DataFrame(data_dict)
print("DataFrame из словаря списков:")
display(df_dict)

# 1.2 Из списка словарей
data_list_dict = [
    {"ID": 1, "Имя": "Иван", "Возраст": 25, "Должность": "Инженер", "Отдел": "IT", "Зарплата": 60000, "Стаж работы": 2},
    {"ID": 2, "Имя": "Ольга", "Возраст": 30, "Должность": "Аналитик", "Отдел": "Маркетинг", "Зарплата": 75000, "Стаж работы": 5},
    {"ID": 3, "Имя": "Алексей", "Возраст": 40, "Должность": "Менеджер", "Отдел": "Продажи", "Зарплата": 90000, "Стаж работы": 15},
    {"ID": 4, "Имя": "Мария", "Возраст": 35, "Должность": "Программист", "Отдел": "IT", "Зарплата": 80000, "Стаж работы": 7},
    {"ID": 5, "Имя": "Сергей", "Возраст": 28, "Должность": "Специалист", "Отдел": "HR", "Зарплата": 50000, "Стаж работы": 3}
]
df_list_dict = pd.DataFrame(data_list_dict)
print("\nDataFrame из списка словарей:")
display(df_list_dict)

# 1.3 Из массива NumPy (случайные возраста от 28 до 69)
np.random.seed(42)
ages = np.random.randint(28, 70, size=10)
df_numpy = pd.DataFrame(ages, columns=["Возраст"])
print("\nDataFrame из массива NumPy (случайные возраста):")
display(df_numpy)

# 1.4 Проверка типов данных с .info()
print("\nИнформация о DataFrame (типы данных):")
df_dict.info()

DataFrame из словаря списков:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

DataFrame из списка словарей:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

DataFrame из массива NumPy (случайные возраста):

   Возраст
0       66
1       56
2       42
3       35
4       48
5       66
6       46
7       50
8       38
9       38

Информация о DataFrame (типы данных):
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           5 non-null      int64
 1   Имя          5 non-null      str
 2   Возраст      5 non-null      int64
 3   Должность    5 non-null      str
 4   Отдел        5 non-null      str
 5   Зарплата     5 non-null      int64
 6   Стаж работы  5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes

In [2]:
# Создаем полную Таблицу 2 (клиенты) для работы
data_clients = {
    "ID": range(1, 21),
    "Имя": ["Иван", "Ольга", "Алексей", "Мария", "Сергей", "Анна", "Дмитрий", "Елена", "Виктор", "Алиса",
            "Павел", "Светлана", "Роман", "Татьяна", "Николай", "Валерия", "Григорий", "Юлия", "Степан", "Васильева"],
    "Возраст": [34, 27, 45, 38, 29, 50, 31, 40, 28, 33, 46, 37, 41, 25, 39, 42, 49, 50, 30, 35],
    "Город": ["Москва", "Санкт-Петербург", "Казань", "Новосибирск", "Екатеринбург", "Воронеж", "Челябинск",
              "Краснодар", "Ростов-на-Дону", "Уфа", "Омск", "Пермь", "Тюмень", "Саратов", "Самара",
              "Волгоград", "Барнаул", "Иркутск", "Хабаровск", "Томск"],
    "Баланс на счете": [120000, 80000, 150000, 200000, 95000, 300000, 140000, 175000, 110000, 98000,
                        250000, 210000, 135000, 155000, 125000, 180000, 275000, 320000, 105000, 90000],
    "Кредитная история": ["Хорошая", "Средняя", "Плохая", "Хорошая", "Средняя", "Отличная", "Средняя",
                          "Хорошая", "Плохая", "Средняя", "Хорошая", "Отличная", "Средняя", "Хорошая",
                          "Средняя", "Плохая", "Отличная", "Хорошая", "Средняя", "Плохая"]
}
df_clients = pd.DataFrame(data_clients)

# 2.1 Сохраняем Таблицу 1 в CSV и читаем обратно
df_dict.to_csv("tabela1.csv", index=False)
df_csv = pd.read_csv("tabela1.csv")
print("CSV файл загружен, первые 5 строк:")
display(df_csv.head())

# 2.2 Сохраняем Таблицу 2 в Excel и читаем обратно
df_clients.to_excel("dados.xlsx", sheet_name="Клиенты", index=False)
df_excel = pd.read_excel("dados.xlsx", sheet_name="Клиенты")
print("\nExcel файл загружен, первые 5 строк:")
display(df_excel.head())

# 2.3 Сохраняем Таблицу 1 в JSON и читаем обратно
df_dict.to_json("tabela1.json", orient="records", indent=4)
df_json = pd.read_json("tabela1.json")
print("\nJSON файл загружен, первые 5 строк:")
display(df_json.head())

CSV файл загружен, первые 5 строк:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

ModuleNotFoundError: No module named 'openpyxl'

In [3]:
# Используем Таблицу 1 с индексом по ID
df = df_dict.copy()
df.set_index("ID", inplace=True)

print("1. Информация о сотруднике с ID = 5 (используя .loc):")
print(df.loc[5])

print("\n2. Возраст третьего сотрудника в таблице (используя .iloc):")
print(f"Возраст: {df.iloc[2, df.columns.get_loc('Возраст')]}")

print("\n3. Название отдела для сотрудника 'Мария' (используя .at):")
# Находим ID Марии
maria_id = df[df["Имя"] == "Мария"].index[0]
print(f"Отдел: {df.at[maria_id, 'Отдел']}")

print("\n4. Зарплата сотрудника в 4-й строке и 5-м столбце (используя .iat):")
print(f"Зарплата: {df.iat[3, 4]}")

print("\n📌 Разница между методами:")
print(".loc[] - доступ по меткам (названиям индексов и столбцов)")
print(".iloc[] - доступ по числовым позициям (номерам строк и столбцов)")
print(".at[] - быстрый доступ к одному элементу по меткам")
print(".iat[] - быстрый доступ к одному элементу по числовым позициям")

1. Информация о сотруднике с ID = 5 (используя .loc):
Имя                Сергей
Возраст                28
Должность      Специалист
Отдел                  HR
Зарплата            50000
Стаж работы             3
Name: 5, dtype: object

2. Возраст третьего сотрудника в таблице (используя .iloc):
Возраст: 40

3. Название отдела для сотрудника 'Мария' (используя .at):
Отдел: IT

4. Зарплата сотрудника в 4-й строке и 5-м столбце (используя .iat):
Зарплата: 80000

📌 Разница между методами:
.loc[] - доступ по меткам (названиям индексов и столбцов)
.iloc[] - доступ по числовым позициям (номерам строк и столбцов)
.at[] - быстрый доступ к одному элементу по меткам
.iat[] - быстрый доступ к одному элементу по числовым позициям

In [4]:
df = df_dict.copy()

# 4.1 Добавляем столбец "Категория зарплаты"
def salary_category(salary):
    if salary < 60000:
        return "Низкая"
    elif salary < 100000:
        return "Средняя"
    else:
        return "Высокая"

df["Категория зарплаты"] = df["Зарплата"].apply(salary_category)
print("DataFrame с новым столбцом 'Категория зарплаты':")
display(df)

# 4.2 Добавляем одного нового сотрудника через .loc
df.loc[21] = ["Антон", 32, "Разработчик", "IT", 85000, 6, "Средняя"]
print("\nDataFrame после добавления сотрудника Антон:")
display(df.tail(3))

# 4.3 Добавляем двух новых сотрудников через pd.concat()
new_employees = pd.DataFrame([
    [22, "Екатерина", 29, "Аналитик", "Маркетинг", 72000, 4, "Средняя"],
    [23, "Максим", 41, "Руководитель", "Продажи", 120000, 12, "Высокая"]
], columns=df.columns)

df = pd.concat([df, new_employees], ignore_index=True)
print("\nDataFrame после добавления двух сотрудников (Екатерина и Максим):")
display(df.tail(3))

DataFrame с новым столбцом 'Категория зарплаты':

,ID,Имя,Возраст,Должность,Отдел,Зарплата,Стаж работы,Категория зарплаты
0,1,Иван,25,Инженер,IT,60000,2,Средняя
1,2,Ольга,30,Аналитик,Маркетинг,75000,5,Средняя
2,3,Алексей,40,Менеджер,Продажи,90000,15,Средняя
3,4,Мария,35,Программист,IT,80000,7,Средняя
4,5,Сергей,28,Специалист,HR,50000,3,Низкая

ValueError: cannot set a row with mismatched columns

In [5]:
df = df_dict.copy()
df["Категория зарплаты"] = df["Зарплата"].apply(salary_category)

# 5.1 Удаляем столбец "Категория зарплаты" с .drop()
df = df.drop(columns=["Категория зарплаты"])
print("После удаления столбца 'Категория зарплаты':")
display(df.head())

# 5.2 Удаляем строку с ID = 10
df = df[df["ID"] != 10]
print("\nПосле удаления строки с ID=10:")
display(df)

# 5.3 Удаляем строки, где Стаж работы < 3 лет
df = df[df["Стаж работы"] >= 3]
print("\nПосле удаления сотрудников со стажем < 3 лет:")
display(df)

# 5.4 Оставляем только столбцы: Имя, Должность, Зарплата
df = df[["Имя", "Должность", "Зарплата"]]
print("\nПосле удаления всех столбцов, кроме Имя, Должность, Зарплата:")
display(df)

После удаления столбца 'Категория зарплаты':

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

После удаления строки с ID=10:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         IT     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

После удаления сотрудников со стажем < 3 лет:

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         IT     80000            7
4   5   Сергей       28   Специалист         HR     50000            3

После удаления всех столбцов, кроме Имя, Должность, Зарплата:

       Имя    Должность  Зарплата
1    Ольга     Аналитик     75000
2  Алексей     Менеджер     90000
3    Мария  Программист     80000
4   Сергей   Специалист     50000

In [6]:
df = df_clients.copy()

# 6.1 Фильтрация через .isin() - клиенты из Москвы или Санкт-Петербурга
filtered_isin = df[df["Город"].isin(["Москва", "Санкт-Петербург"])]
print("1. Клиенты из Москвы или Санкт-Петербурга:")
display(filtered_isin)

# 6.2 Фильтрация через .between() - баланс от 100 000 до 250 000
filtered_between = df[df["Баланс на счете"].between(100000, 250000)]
print("\n2. Клиенты с балансом от 100 000 до 250 000:")
display(filtered_between)

# 6.3 Фильтрация через .query() - кредитная история "Хорошая" и баланс > 150 000
filtered_query = df.query("`Кредитная история` == 'Хорошая' and `Баланс на счете` > 150000")
print("\n3. Клиенты с кредитной историей 'Хорошая' и балансом > 150 000:")
display(filtered_query)

1. Клиенты из Москвы или Санкт-Петербурга:

   ID    Имя  Возраст            Город  Баланс на счете Кредитная история
0   1   Иван       34           Москва           120000           Хорошая
1   2  Ольга       27  Санкт-Петербург            80000           Средняя

2. Клиенты с балансом от 100 000 до 250 000:

    ID       Имя  Возраст           Город  Баланс на счете Кредитная история
0    1      Иван       34          Москва           120000           Хорошая
2    3   Алексей       45          Казань           150000            Плохая
3    4     Мария       38     Новосибирск           200000           Хорошая
6    7   Дмитрий       31       Челябинск           140000           Средняя
7    8     Елена       40       Краснодар           175000           Хорошая
8    9    Виктор       28  Ростов-на-Дону           110000            Плохая
10  11     Павел       46            Омск           250000           Хорошая
11  12  Светлана       37           Пермь           210000          Отличная
12  13     Роман       41          Тюмень           135000           Средняя
13  14   Татьяна       25         Саратов           155000           Хорошая
14  15   Николай       39          Самара           125000           Средняя
15  16   Валерия       42       Волгоград           180000            Плохая
18  19    Степан       30       Хабаровск           105000           Средняя

3. Клиенты с кредитной историей 'Хорошая' и балансом > 150 000:

    ID      Имя  Возраст        Город  Баланс на счете Кредитная история
3    4    Мария       38  Новосибирск           200000           Хорошая
7    8    Елена       40    Краснодар           175000           Хорошая
10  11    Павел       46         Омск           250000           Хорошая
13  14  Татьяна       25      Саратов           155000           Хорошая
17  18     Юлия       50      Иркутск           320000           Хорошая

In [3]:
import pandas as pd

data_clients = {
    "ID": list(range(1, 21)),
    "Имя": ["Иван", "Ольга", "Алексей", "Мария", "Сергей", "Анна", "Дмитрий", "Елена", 
            "Виктор", "Алиса", "Павел", "Светлана", "Роман", "Татьяна", "Николай", 
            "Валерия", "Григорий", "Юлия", "Степан", "Васильева"],
    "Возраст": [34, 27, 45, 38, 29, 50, 31, 40, 28, 33, 46, 37, 41, 25, 39, 42, 49, 50, 30, 35],
    "Город": ["Москва", "Санкт-Петербург", "Казань", "Новосибирск", "Екатеринбург", "Воронеж", 
              "Челябинск", "Краснодар", "Ростов-на-Дону", "Уфа", "Омск", "Пермь", "Тюмень", 
              "Саратов", "Самара", "Волгоград", "Барнаул", "Иркутск", "Хабаровск", "Томск"],
    "Баланс на счете": [120000, 80000, 150000, 200000, 95000, 300000, 140000, 175000, 
                        110000, 98000, 250000, 210000, 135000, 155000, 125000, 180000, 
                        275000, 320000, 105000, 90000],
    "Кредитная история": ["Хорошая", "Средняя", "Плохая", "Хорошая", "Средняя", "Отличная", 
                          "Средняя", "Хорошая", "Плохая", "Средняя", "Хорошая", "Отличная", 
                          "Средняя", "Хорошая", "Средняя", "Плохая", "Отличная", "Хорошая", 
                          "Средняя", "Плохая"]
}
df_clients = pd.DataFrame(data_clients)

In [4]:
df = df_clients.copy()

print("1. Количество непустых значений в каждом столбце (.count()):")
print(df.count())

print("\n2. Частота встречаемости значений в столбце 'Город' (.value_counts()):")
print(df["Город"].value_counts())

print("\n3. Количество уникальных значений (.unique()):")
print(f"Уникальных городов: {df['Город'].unique()}")
print(f"Уникальных возрастов: {df['Возраст'].unique()}")
print(f"Уникальных балансов: {df['Баланс на счете'].unique()}")

1. Количество непустых значений в каждом столбце (.count()):
ID                   20
Имя                  20
Возраст              20
Город                20
Баланс на счете      20
Кредитная история    20
dtype: int64

2. Частота встречаемости значений в столбце 'Город' (.value_counts()):
Город
Москва             1
Санкт-Петербург    1
Казань             1
Новосибирск        1
Екатеринбург       1
Воронеж            1
Челябинск          1
Краснодар          1
Ростов-на-Дону     1
Уфа                1
Омск               1
Пермь              1
Тюмень             1
Саратов            1
Самара             1
Волгоград          1
Барнаул            1
Иркутск            1
Хабаровск          1
Томск              1
Name: count, dtype: int64

3. Количество уникальных значений (.unique()):
Уникальных городов: <StringArray>
[         'Москва', 'Санкт-Петербург',          'Казань',     'Новосибирск',
    'Екатеринбург',         'Воронеж',       'Челябинск',       'Краснодар',
  'Ростов-на-Дону',             'Уфа',            'Омск',           'Пермь',
          'Тюмень',         'Саратов',          'Самара',       'Волгоград',
         'Барнаул',         'Иркутск',       'Хабаровск',           'Томск']
Length: 20, dtype: str
Уникальных возрастов: [34 27 45 38 29 50 31 40 28 33 46 37 41 25 39 42 49 30 35]
Уникальных балансов: [120000  80000 150000 200000  95000 300000 140000 175000 110000  98000
 250000 210000 135000 155000 125000 180000 275000 320000 105000  90000]

In [7]:
import pandas as pd
from IPython.display import display

# Создаем Таблицу 3 с пропусками (ИСПРАВЛЕННАЯ)
data_nan = {
    "ID": list(range(1, 21)),
    "Имя": ["Иван", "Ольга", "Алексей", "Мария", "Сергей", None, "Дмитрий", "Елена", 
            "Виктор", "Алиса", "Павел", None, "Роман", "Татьяна", "Николай", "Валерия", 
            "Григорий", "Юлия", "Степан", "Васильева"],
    "Возраст": [34.0, 27.0, None, 38.0, 29.0, 50.0, 31.0, 40.0, None, 33.0, 
                46.0, 37.0, 41.0, 25.0, None, 42.0, 49.0, None, 30.0, 35.0],
    "Город": ["Москва", "Санкт-Петербург", "Казань", None, "Екатеринбург", "Воронеж", 
              None, "Краснодар", "Ростов-на-Дону", "Уфа", "Омск", "Пермь", None, 
              "Саратов", "Самара", None, "Барнаул", "Иркутск", "Хабаровск", "Томск"],
    "Баланс на счете": [120000.0, None, 150000.0, 200000.0, None, 300000.0, 140000.0, 
                        175000.0, 110000.0, None, 250000.0, 210000.0, 135000.0, 
                        155000.0, 125000.0, None, 275000.0, 320000.0, 105000.0, 90000.0],
    "Кредитная история": ["Хорошая", "Средняя", "Плохая", "Хорошая", None, "Отличная", 
                          "Средняя", "Хорошая", None, "Средняя", "Хорошая", "Отличная", 
                          "Средняя", "Хорошая", "Средняя", "Плохая", "Отличная", 
                          "Хорошая", "Средняя", "Плохая"]
}

df_nan = pd.DataFrame(data_nan)

print("1. Количество NaN в каждом столбце (.isna().sum()):")
print(df_nan.isna().sum())

print("\n2. Количество заполненных значений в каждом столбце (.notna().sum()):")
print(df_nan.notna().sum())

print("\n3. DataFrame только с строками без пропусков (.dropna()):")
df_clean = df_nan.dropna()
display(df_clean)

1. Количество NaN в каждом столбце (.isna().sum()):
ID                   0
Имя                  2
Возраст              4
Город                4
Баланс на счете      4
Кредитная история    2
dtype: int64

2. Количество заполненных значений в каждом столбце (.notna().sum()):
ID                   20
Имя                  18
Возраст              16
Город                16
Баланс на счете      16
Кредитная история    18
dtype: int64

3. DataFrame только с строками без пропусков (.dropna()):

    ID        Имя  Возраст      Город  Баланс на счете Кредитная история
0    1       Иван     34.0     Москва         120000.0           Хорошая
7    8      Елена     40.0  Краснодар         175000.0           Хорошая
10  11      Павел     46.0       Омск         250000.0           Хорошая
13  14    Татьяна     25.0    Саратов         155000.0           Хорошая
16  17   Григорий     49.0    Барнаул         275000.0          Отличная
18  19     Степан     30.0  Хабаровск         105000.0           Средняя
19  20  Васильева     35.0      Томск          90000.0            Плохая

In [ ]:
import pandas as pd
import os

data_file = "products.csv"  # Mudamos para CSV

# Загружаем существующий DataFrame или создаем новый
if os.path.exists(data_file):
    df = pd.read_csv(data_file, encoding="utf-8")
    print(f" Загружено {len(df)} записей из {data_file}")
else:
    df = pd.DataFrame(columns=["Название товара", "Название магазина", "Стоимость товара"])
    print(" Создан новый пустой DataFrame")

# Интерактивное добавление товаров
print("\n--- Добавление новых товаров ---")
print("(Для выхода оставьте название товара пустым)")

while True:
    name = input("Название товара (Enter для выхода): ").strip()
    if not name:
        break
    shop = input("Название магазина: ").strip()
    try:
        price = float(input("Стоимость товара (руб): "))
    except ValueError:
        print(" Некорректная цена! Товар не добавлен.")
        continue
    
    df.loc[len(df)] = [name, shop, price]
    print(f"✅ Товар '{name}' добавлен!\n")

# Сортировка по алфавиту
if not df.empty:
    df = df.sort_values(by="Название товара").reset_index(drop=True)
else:
    print("\n Нет данных для сортировки")

# Сохранение в CSV
df.to_csv(data_file, index=False, encoding="utf-8")
print(f"\n Данные сохранены в {data_file}")

# Вывод всех товаров
print("\n" + "="*60)
print("СПИСОК ВСЕХ ТОВАРОВ (в алфавитном порядке):")
print("="*60)
if not df.empty:
    for idx, row in df.iterrows():
        print(f"{idx+1}. {row['Название товара']} | {row['Название магазина']} | {row['Стоимость товара']:.2f} руб")
else:
    print(" Список товаров пуст")
print("="*60)

# Поиск товара (интерактивный)
print("\n--- ПОИСК ТОВАРА ---")
search_name = input("Введите название товара для поиска (Enter для пропуска): ").strip()

if search_name and not df.empty:
    result = df[df["Название товара"] == search_name]
    if result.empty:
        print(f" Товар '{search_name}' не найден.")
    else:
        print(f"\n Информация о товаре '{search_name}':")
        print(result.to_string(index=False))
elif search_name and df.empty:
    print(" Нет данных для поиска")
else:
    print("Поиск пропущен")

✅ Загружено 3 записей из products.csv

--- Добавление новых товаров ---
(Для выхода оставьте название товара пустым)

Название товара (Enter для выхода):  Молоко
Название магазина:  Пятёрочка
Стоимость товара (руб):  89.50

✅ Товар 'Молоко' добавлен!

Название товара (Enter для выхода):  Хлеб
Название магазина:  Магнит
Стоимость товара (руб):  45.00

✅ Товар 'Хлеб' добавлен!

Название товара (Enter для выхода):  Яблоки
Название магазина:  Ашан
Стоимость товара (руб):  120.00

✅ Товар 'Яблоки' добавлен!